int8 SET_TASK = 1
int8 SET_POSTURE = 2
int8 GET_TASK = 3
int8 GET_POSTURE = 4
int8 mode
float64[] goal
##float64[] amax
##float64[] vmax
float64[] kp
float64[] kd
---
bool ok
string errstr
##float64[] pos
##float64[] vel
float64[] goal
##float64[] amax
##float64[] vmax
float64[] kp
float64[] kd
