string com_type
string com_name
string param_name
---
int64 param_type
StringParamChannel[] string_channel
IntegerParamChannel[] integer_channel
RealParamChannel[] real_channel
VectorParamChannel[] vector_channel
MatrixParamChannel[] matrix_channel
bool ok
string errstr
